### ISSUE TITLE
shipit_static_analysis: Catch problems on lines not directly modified by a patch

### ISSUE THREAD

**Issue by glandium** [mozilla-releng/services#701] opened 2017-11-03 10:29 UTC
**MozReview URL:** https://reviewboard.mozilla.org/r/196088/#issue-summary

**Problem:** The patch queue is large and does many changes, but the core of the problem is this:

The second patch changed code like:
```
  if (foo) {
    aSize = ...
  } else if (bar) {
```
To:
```
  if (foo) {
    return ...
  } else if (bar) {
```

In other words, it's the cause of `readability-else-after-return` problem.
But, that problem was only found on a later patch, that touches the else line.

If I hadn't touched the else line in a later patch, this wouldn't have been caught.

**Comment by jankeromnes** [comment] 2017-11-07 14:05
Interesting, thanks a lot for reporting this problem!

Indeed clangbot will only complain about lines you actually modified, in order not to bother you with pre-existing issues that have nothing to do with your change. We are not yet able to precisely differentiate problems caused by a patch from pre-existing issues, so we use this very simple heuristic, but it does have its limits (e.g. it's not able to catch macro-related issues, since the symptom is on a different line than the cause, and the same thing happens for adding a `return` before an `else`).

I'm not sure how we could improve our detection of "problems actually caused by this patch" in order to cover this corner case (obvious solutions like "run analysis before and after the patch" can be tricky because we're not able to identify common defects across line/file changes or more involved refactors).

I know that tools like Git tend to deal with consequent lines like they're the same line (e.g. triggering conflicts when two separate lines were changed but happened to be right next to each other), but doing that in clangbot would only fix the problem when `else` is on the line immediately after the added `return` (e.g. blank lines will break this heuristic), and it would increase the number of pre-existing issues being reported (i.e. every time you modify a line right next to a pre-existing problem).

**Comment by jankeromnes** [comment] 2018-07-02 14:30
Note: We call our current heuristic (described above) `IN_PATCH`, and are working on a better way to detect new issues called `BEFORE_AFTER` (which runs analysis once before the patch and once after, in order to detect which defects were introduced by the patch, regardless of which line it lives on).

Hence, closing this issue as a "duplicate" of the meta-issue #1236. Thanks again!

**Closed by jankeromnes** 2018-07-02 14:30 UTC
Labels: app:shipit_static_analysis, kind:enhancement
