### ISSUE TITLE
shipit_static_analysis: automated review comments not having the correct case

### ISSUE THREAD

**Issue by fqueze** [mozilla-releng/services#1248] opened 2018-06-29 12:43 UTC
**MozReview URL:** https://reviewboard.mozilla.org/r/…

**Problem:** 
https://bugzilla.mozilla.org/show_bug.cgi?id=947838#c22 reports:
Error: Use cu rather than components.utils [eslint: mozilla/use-cc-etc]
 but the actual eslint report is:
424:5  error  Use Cu rather than Components.utils  mozilla/use-cc-etc (eslint)

**Comment by jankeromnes** [comment] 2018-07-02 14:32
Thanks a lot for reporting this issue! I'm closing it as a duplicate of #997, but I'll look into fixing it shortly.

**Closed by jankeromnes** 2018-07-02 14:32 UTC
Labels: app:shipit_static_analysis, kind:bug
